steps:
  #Build the image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build','-t','asia-south1-docker.pkg.dev/spring-melody-456515-j0/try-first-project-artifact-repo/try-first-project','.']

  #Push the image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push','asia-south1-docker.pkg.dev/spring-melody-456515-j0/try-first-project-artifact-repo/try-first-project']

options:
  logging: CLOUD_LOGGING_ONLY