steps:
  #First Clone from github Repository
  - name: 'clone the project'
    entrypoint: 'git'
    args: ['clone','https://github.com/Ravindra-87/Try-FirsT-Project.git']


    #Build the image
  - name: 'build the  docker image'
    args: ['build','-t','asia-south1-docker.pkg.dev/spring-melody-456515-j0/try-first-project-artifact-repo/try-first-project','.']

  #Push the image
  - name: 'push the docker image to GAR'
    args: ['push','asia-south1-docker.pkg.dev/spring-melody-456515-j0/try-first-project-artifact-repo/try-first-project']

options:
  logging: CLOUD_LOGGING_ONLY