steps:
  #First Clone from GitHub Repository
  - name: 'gcr.io/cloud-builders/git'
    id: 'Clone the project from git hub'
    entrypoint: 'git'
    args: ['clone','https://github.com/Ravindra-87/Try-FirsT-Project.git']

  #Maven Build
  - name: 'gcr.io/cloud-builders/mvn'
    id: 'Build the maven artifact'
    args:
      - 'clean'
      - 'install'
      - '-DskipTests'
    dir: '.'  # Assuming the pom.xml file is in the root of your repo

    #Build the image
  - name: 'gcr.io/cloud-builders/docker'
    id: 'Build the docker image'
    args: ['build','-t','asia-east1-docker.pkg.dev/try-first-project-456718/try-first-project-docker-repo/try-first-project:latest','.']

   #Push the image
  - name: 'gcr.io/cloud-builders/docker'
    id: 'Push the docker image'
    args: ['push','asia-east1-docker.pkg.dev/try-first-project-456718/try-first-project-docker-repo/try-first-project:latest']


    # deploy container image to GKE
  - name: "gcr.io/cloud-builders/gke-deploy"
    args:
      - run
      - --filename=kubernetes/deployment.yaml
      - --location=africa-south1
      - --cluster=dev-cluster
      - --image=asia-east1-docker.pkg.dev/try-first-project-456718/try-first-project-docker-repo/try-first-project:latest


#  # Deploy changes to kubernetes config files - Stage 3
#  - name: 'gcr.io/cloud-builders/kubectl'
#    id: 'deploy container image to GKE'
#    args: ["apply", "-f", "kubernetes/"]
#    env:
#      - 'CLOUDSDK_COMPUTE_ZONE=africa-south1'
#      - 'CLOUDSDK_CONTAINER_CLUSTER=dev-cluster'

options:
  logging: CLOUD_LOGGING_ONLY