steps:
  #First Clone from github Repository
  - name: 'gcr.io/cloud-builders/git'
    id: 'Clone the project from git hub'
    entrypoint: 'git'
    args: ['clone','https://github.com/Ravindra-87/Try-FirsT-Project.git']

  #Maven Build
  - name: 'gcr.io/cloud-builders/mvn'
    id: 'Build the maven artifact'
    args:
      - 'clean'
      - 'install'
      - '-DskipTests'
    dir: '.'  # Assuming the pom.xml file is in the root of your repo

  # Generate the timestamp and save it to a file
  - name: 'gcr.io/cloud-builders/gcloud'
    id: 'Generate timestamp'
    entrypoint: 'bash'
    script: |
      TIMESTAMP=$(date +%Y-%m-%d-%H-%M-%S)
      echo "Generated timestamp: $TIMESTAMP"
      echo "$TIMESTAMP" > /workspace/timestamp.txt

  #Build the image
#  - name: 'gcr.io/cloud-builders/docker'
#    id: 'Build the docker image'
#    args: ['build','-t','asia-east1-docker.pkg.dev/try-first-project-456718/try-first-project-gar-rep/try-first-project:$(date +%Y-%m-%d-%H-%M-%S)','.']

  - name: 'gcr.io/cloud-builders/docker'
    id: 'Build the docker image with timestamp'
    entrypoint: 'bash'
    args:
      - -c
      - |
        TIMESTAMP=$(date +%Y-%m-%d-%H-%M-%S)
        docker build -t asia-east1-docker.pkg.dev/try-first-project-456718/try-first-project-gar-rep/try-first-project:$TIMESTAMP .


  #Push the image
  - name: 'gcr.io/cloud-builders/docker'
    id: 'Push the docker image'
    args: ['push','asia-east1-docker.pkg.dev/try-first-project-456718/try-first-project-gar-rep/try-first-project:latest']

    # deploy container image to GKE
  - name: "gcr.io/cloud-builders/gke-deploy"
    args:
      - run
      - --filename=kubernetes/deployment.yaml
      - --location=us-central1
      - --cluster=dev-cluster

options:
  logging: CLOUD_LOGGING_ONLY