apiVersion: apps/v1
kind: Deployment
metadata:
  name: try-first-project
spec:
  replicas: 1
  selector:
    matchLabels:
      app: try-first-project-app
  template:
    metadata:
      labels:
        app: try-first-project-app
    spec:
      containers:
        - name: try-first-project
          image: asia-east1-docker.pkg.dev/try-first-project-456718/try-first-project-gar-rep/try-first-project
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: try-first-project-service
spec:
  type: LoadBalancer
  selector:
    app: try-first-project-app
  ports:
    - port: 80
      targetPort: 80