apiVersion: v1
kind: Secret
metadata:
  name: secret-db-password
  namespace: default  # Optional, default is usually fine
type: Opaque
data:
  password: QXlucmFuZCM4Nw== # The base64-encoded password