apiVersion: v1
kind: Service
metadata:
  name: try-first-project-service
spec:
  type: NodePort
  selector:
    app: try-first-project-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 30080