apiVersion: v1
kind: Service
metadata:
  name: try-first-project-service
  namespace: dev-first-project-456718
spec:
  type: LoadBalancer
  selector:
    app: try-first-project-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080